services:
  vaultwarden:
    container_name: vaultwarden
    environment:
      ATTACHMENTS_ENABLED: 'true'
    image: vaultwarden/server:latest
    restart: no
    volumes:
    - ./data/vaultwarden:/data

  caddy:
    image: caddy:2
    container_name: caddy
    restart: no
    ports:
      - 8446:8443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy:/data
      - ./data/caddy/config:/config
